#############################################################################
# Makefile for building: qopenglwidget
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  qopenglwidget.pro
# Template: app
# Command: /home/julien/raspi/qt5/bin/qmake -o Makefile qopenglwidget.pro -spec devices/linux-rasp-pi-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc
CXX           = /home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/julien/raspi/sysroot -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/julien/raspi/sysroot -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../qt5pi/include -I../qt5pi/include/QtWidgets -I../qt5pi/include/QtGui -I../qt5pi/include/QtCore -I. -I../sysroot/opt/vc/include -I../sysroot/opt/vc/include/interface/vcos/pthreads -I../sysroot/opt/vc/include/interface/vmcs_host/linux -I. -I../qt5/mkspecs/devices/linux-rasp-pi-g++
QMAKE         = /home/julien/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/julien/raspi/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/julien/raspi/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qopenglwidget1.0.0
DISTDIR = /home/julien/raspi/JulsEfis/.tmp/qopenglwidget1.0.0
LINK          = /home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/home/julien/raspi/sysroot -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/home/julien/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/julien/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/julien/raspi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L/home/julien/raspi/sysroot/opt/vc/lib -lbcm2835 -L/home/julien/raspi/qt5pi/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = /home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwidget.cpp \
		EM7180.cpp \
		EM7180_Master.cpp \
		gui.cpp \
		i2c_comm.cpp moc_mainwidget.cpp \
		moc_gui.cpp \
		moc_i2c_comm.cpp
OBJECTS       = main.o \
		mainwidget.o \
		EM7180.o \
		EM7180_Master.o \
		gui.o \
		i2c_comm.o \
		moc_mainwidget.o \
		moc_gui.o \
		moc_i2c_comm.o
DIST          = ../qt5/mkspecs/features/spec_pre.prf \
		../qt5/mkspecs/common/unix.conf \
		../qt5/mkspecs/common/linux.conf \
		../qt5/mkspecs/common/sanitize.conf \
		../qt5/mkspecs/common/gcc-base.conf \
		../qt5/mkspecs/common/gcc-base-unix.conf \
		../qt5/mkspecs/common/g++-base.conf \
		../qt5/mkspecs/common/g++-unix.conf \
		../qt5/mkspecs/qdevice.pri \
		../qt5/mkspecs/features/device_config.prf \
		../qt5/mkspecs/devices/common/linux_device_pre.conf \
		../qt5/mkspecs/devices/common/linux_device_post.conf \
		../qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../qt5/mkspecs/qconfig.pri \
		../qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt5/mkspecs/modules/qt_lib_core.pri \
		../qt5/mkspecs/modules/qt_lib_core_private.pri \
		../qt5/mkspecs/modules/qt_lib_dbus.pri \
		../qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_gui.pri \
		../qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_network.pri \
		../qt5/mkspecs/modules/qt_lib_network_private.pri \
		../qt5/mkspecs/modules/qt_lib_opengl.pri \
		../qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_sql.pri \
		../qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../qt5/mkspecs/modules/qt_lib_testlib.pri \
		../qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_widgets.pri \
		../qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../qt5/mkspecs/modules/qt_lib_xml.pri \
		../qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt5/mkspecs/features/qt_functions.prf \
		../qt5/mkspecs/features/qt_config.prf \
		../qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		../qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt5/mkspecs/features/exclusive_builds.prf \
		../qt5/mkspecs/features/toolchain.prf \
		../qt5/mkspecs/features/default_pre.prf \
		../qt5/mkspecs/features/resolve_config.prf \
		../qt5/mkspecs/features/default_post.prf \
		../qt5/mkspecs/features/qml_debug.prf \
		../qt5/mkspecs/features/warn_on.prf \
		../qt5/mkspecs/features/qt.prf \
		../qt5/mkspecs/features/resources.prf \
		../qt5/mkspecs/features/moc.prf \
		../qt5/mkspecs/features/unix/opengl.prf \
		../qt5/mkspecs/features/uic.prf \
		../qt5/mkspecs/features/unix/thread.prf \
		../qt5/mkspecs/features/qmake_use.prf \
		../qt5/mkspecs/features/file_copies.prf \
		../qt5/mkspecs/features/testcase_targets.prf \
		../qt5/mkspecs/features/exceptions.prf \
		../qt5/mkspecs/features/yacc.prf \
		../qt5/mkspecs/features/lex.prf \
		qopenglwidget.pro mainwidget.h \
		EM7180.h \
		EM7180_Master.h \
		gui.h \
		i2c_comm.h \
		bcm2835.h main.cpp \
		mainwidget.cpp \
		EM7180.cpp \
		EM7180_Master.cpp \
		gui.cpp \
		i2c_comm.cpp
QMAKE_TARGET  = qopenglwidget
DESTDIR       = 
TARGET        = qopenglwidget


first: all
####### Build rules

$(TARGET): ui_mainwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qopenglwidget.pro ../qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf ../qt5/mkspecs/features/spec_pre.prf \
		../qt5/mkspecs/common/unix.conf \
		../qt5/mkspecs/common/linux.conf \
		../qt5/mkspecs/common/sanitize.conf \
		../qt5/mkspecs/common/gcc-base.conf \
		../qt5/mkspecs/common/gcc-base-unix.conf \
		../qt5/mkspecs/common/g++-base.conf \
		../qt5/mkspecs/common/g++-unix.conf \
		../qt5/mkspecs/qdevice.pri \
		../qt5/mkspecs/features/device_config.prf \
		../qt5/mkspecs/devices/common/linux_device_pre.conf \
		../qt5/mkspecs/devices/common/linux_device_post.conf \
		../qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../qt5/mkspecs/qconfig.pri \
		../qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qt5/mkspecs/modules/qt_lib_core.pri \
		../qt5/mkspecs/modules/qt_lib_core_private.pri \
		../qt5/mkspecs/modules/qt_lib_dbus.pri \
		../qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_gui.pri \
		../qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_network.pri \
		../qt5/mkspecs/modules/qt_lib_network_private.pri \
		../qt5/mkspecs/modules/qt_lib_opengl.pri \
		../qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_sql.pri \
		../qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../qt5/mkspecs/modules/qt_lib_testlib.pri \
		../qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../qt5/mkspecs/modules/qt_lib_widgets.pri \
		../qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../qt5/mkspecs/modules/qt_lib_xml.pri \
		../qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../qt5/mkspecs/features/qt_functions.prf \
		../qt5/mkspecs/features/qt_config.prf \
		../qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		../qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../qt5/mkspecs/features/exclusive_builds.prf \
		../qt5/mkspecs/features/toolchain.prf \
		../qt5/mkspecs/features/default_pre.prf \
		../qt5/mkspecs/features/resolve_config.prf \
		../qt5/mkspecs/features/default_post.prf \
		../qt5/mkspecs/features/qml_debug.prf \
		../qt5/mkspecs/features/warn_on.prf \
		../qt5/mkspecs/features/qt.prf \
		../qt5/mkspecs/features/resources.prf \
		../qt5/mkspecs/features/moc.prf \
		../qt5/mkspecs/features/unix/opengl.prf \
		../qt5/mkspecs/features/uic.prf \
		../qt5/mkspecs/features/unix/thread.prf \
		../qt5/mkspecs/features/qmake_use.prf \
		../qt5/mkspecs/features/file_copies.prf \
		../qt5/mkspecs/features/testcase_targets.prf \
		../qt5/mkspecs/features/exceptions.prf \
		../qt5/mkspecs/features/yacc.prf \
		../qt5/mkspecs/features/lex.prf \
		qopenglwidget.pro \
		../qt5pi/lib/libQt5Widgets.prl \
		../qt5pi/lib/libQt5Gui.prl \
		../qt5pi/lib/libQt5Core.prl
	$(QMAKE) -o Makefile qopenglwidget.pro -spec devices/linux-rasp-pi-g++ CONFIG+=debug CONFIG+=qml_debug
../qt5/mkspecs/features/spec_pre.prf:
../qt5/mkspecs/common/unix.conf:
../qt5/mkspecs/common/linux.conf:
../qt5/mkspecs/common/sanitize.conf:
../qt5/mkspecs/common/gcc-base.conf:
../qt5/mkspecs/common/gcc-base-unix.conf:
../qt5/mkspecs/common/g++-base.conf:
../qt5/mkspecs/common/g++-unix.conf:
../qt5/mkspecs/qdevice.pri:
../qt5/mkspecs/features/device_config.prf:
../qt5/mkspecs/devices/common/linux_device_pre.conf:
../qt5/mkspecs/devices/common/linux_device_post.conf:
../qt5/mkspecs/devices/common/linux_arm_device_post.conf:
../qt5/mkspecs/qconfig.pri:
../qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../qt5/mkspecs/modules/qt_lib_concurrent.pri:
../qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../qt5/mkspecs/modules/qt_lib_core.pri:
../qt5/mkspecs/modules/qt_lib_core_private.pri:
../qt5/mkspecs/modules/qt_lib_dbus.pri:
../qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
../qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../qt5/mkspecs/modules/qt_lib_gui.pri:
../qt5/mkspecs/modules/qt_lib_gui_private.pri:
../qt5/mkspecs/modules/qt_lib_input_support_private.pri:
../qt5/mkspecs/modules/qt_lib_network.pri:
../qt5/mkspecs/modules/qt_lib_network_private.pri:
../qt5/mkspecs/modules/qt_lib_opengl.pri:
../qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../qt5/mkspecs/modules/qt_lib_printsupport.pri:
../qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../qt5/mkspecs/modules/qt_lib_service_support_private.pri:
../qt5/mkspecs/modules/qt_lib_sql.pri:
../qt5/mkspecs/modules/qt_lib_sql_private.pri:
../qt5/mkspecs/modules/qt_lib_testlib.pri:
../qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../qt5/mkspecs/modules/qt_lib_widgets.pri:
../qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../qt5/mkspecs/modules/qt_lib_xml.pri:
../qt5/mkspecs/modules/qt_lib_xml_private.pri:
../qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../qt5/mkspecs/features/qt_functions.prf:
../qt5/mkspecs/features/qt_config.prf:
../qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
../qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
../qt5/mkspecs/features/exclusive_builds.prf:
../qt5/mkspecs/features/toolchain.prf:
../qt5/mkspecs/features/default_pre.prf:
../qt5/mkspecs/features/resolve_config.prf:
../qt5/mkspecs/features/default_post.prf:
../qt5/mkspecs/features/qml_debug.prf:
../qt5/mkspecs/features/warn_on.prf:
../qt5/mkspecs/features/qt.prf:
../qt5/mkspecs/features/resources.prf:
../qt5/mkspecs/features/moc.prf:
../qt5/mkspecs/features/unix/opengl.prf:
../qt5/mkspecs/features/uic.prf:
../qt5/mkspecs/features/unix/thread.prf:
../qt5/mkspecs/features/qmake_use.prf:
../qt5/mkspecs/features/file_copies.prf:
../qt5/mkspecs/features/testcase_targets.prf:
../qt5/mkspecs/features/exceptions.prf:
../qt5/mkspecs/features/yacc.prf:
../qt5/mkspecs/features/lex.prf:
qopenglwidget.pro:
../qt5pi/lib/libQt5Widgets.prl:
../qt5pi/lib/libQt5Gui.prl:
../qt5pi/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qopenglwidget.pro -spec devices/linux-rasp-pi-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwidget.h EM7180.h EM7180_Master.h gui.h i2c_comm.h bcm2835.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwidget.cpp EM7180.cpp EM7180_Master.cpp gui.cpp i2c_comm.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../qt5/mkspecs/features/data/dummy.cpp
	/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++ -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/julien/raspi/sysroot -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwidget.cpp moc_gui.cpp moc_i2c_comm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwidget.cpp moc_gui.cpp moc_i2c_comm.cpp
moc_mainwidget.cpp: ../qt5pi/include/QtWidgets/QWidget \
		../qt5pi/include/QtWidgets/qwidget.h \
		../qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../qt5pi/include/QtGui/qtguiglobal.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtGui/qtgui-config.h \
		../qt5pi/include/QtWidgets/qtwidgets-config.h \
		../qt5pi/include/QtGui/qwindowdefs.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtGui/qwindowdefs_win.h \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		../qt5pi/include/QtCore/qmargins.h \
		../qt5pi/include/QtGui/qpaintdevice.h \
		../qt5pi/include/QtCore/qrect.h \
		../qt5pi/include/QtCore/qsize.h \
		../qt5pi/include/QtCore/qpoint.h \
		../qt5pi/include/QtGui/qpalette.h \
		../qt5pi/include/QtGui/qcolor.h \
		../qt5pi/include/QtGui/qrgb.h \
		../qt5pi/include/QtGui/qrgba64.h \
		../qt5pi/include/QtGui/qbrush.h \
		../qt5pi/include/QtCore/qvector.h \
		../qt5pi/include/QtGui/qmatrix.h \
		../qt5pi/include/QtGui/qpolygon.h \
		../qt5pi/include/QtGui/qregion.h \
		../qt5pi/include/QtCore/qdatastream.h \
		../qt5pi/include/QtCore/qiodevice.h \
		../qt5pi/include/QtCore/qline.h \
		../qt5pi/include/QtGui/qtransform.h \
		../qt5pi/include/QtGui/qpainterpath.h \
		../qt5pi/include/QtGui/qimage.h \
		../qt5pi/include/QtGui/qpixelformat.h \
		../qt5pi/include/QtGui/qpixmap.h \
		../qt5pi/include/QtCore/qsharedpointer.h \
		../qt5pi/include/QtCore/qshareddata.h \
		../qt5pi/include/QtCore/qhash.h \
		../qt5pi/include/QtCore/qsharedpointer_impl.h \
		../qt5pi/include/QtGui/qfont.h \
		../qt5pi/include/QtGui/qfontmetrics.h \
		../qt5pi/include/QtGui/qfontinfo.h \
		../qt5pi/include/QtWidgets/qsizepolicy.h \
		../qt5pi/include/QtGui/qcursor.h \
		../qt5pi/include/QtGui/qkeysequence.h \
		../qt5pi/include/QtGui/qevent.h \
		../qt5pi/include/QtCore/qvariant.h \
		../qt5pi/include/QtCore/qmap.h \
		../qt5pi/include/QtCore/qdebug.h \
		../qt5pi/include/QtCore/qtextstream.h \
		../qt5pi/include/QtCore/qlocale.h \
		../qt5pi/include/QtCore/qset.h \
		../qt5pi/include/QtCore/qcontiguouscache.h \
		../qt5pi/include/QtCore/qurl.h \
		../qt5pi/include/QtCore/qurlquery.h \
		../qt5pi/include/QtCore/qfile.h \
		../qt5pi/include/QtCore/qfiledevice.h \
		../qt5pi/include/QtGui/qvector2d.h \
		../qt5pi/include/QtGui/qtouchdevice.h \
		../qt5pi/include/QtCore/QtCore \
		../qt5pi/include/QtCore/QtCoreDepends \
		../qt5pi/include/QtCore/qabstractanimation.h \
		../qt5pi/include/QtCore/qabstracteventdispatcher.h \
		../qt5pi/include/QtCore/qeventloop.h \
		../qt5pi/include/QtCore/qabstractitemmodel.h \
		../qt5pi/include/QtCore/qabstractnativeeventfilter.h \
		../qt5pi/include/QtCore/qabstractproxymodel.h \
		../qt5pi/include/QtCore/qabstractstate.h \
		../qt5pi/include/QtCore/qabstracttransition.h \
		../qt5pi/include/QtCore/qanimationgroup.h \
		../qt5pi/include/QtCore/qarraydataops.h \
		../qt5pi/include/QtCore/qarraydatapointer.h \
		../qt5pi/include/QtCore/qbasictimer.h \
		../qt5pi/include/QtCore/qbitarray.h \
		../qt5pi/include/QtCore/qbuffer.h \
		../qt5pi/include/QtCore/qbytearraymatcher.h \
		../qt5pi/include/QtCore/qcache.h \
		../qt5pi/include/QtCore/qcollator.h \
		../qt5pi/include/QtCore/qcommandlineoption.h \
		../qt5pi/include/QtCore/qcommandlineparser.h \
		../qt5pi/include/QtCore/qcoreapplication.h \
		../qt5pi/include/QtCore/qcryptographichash.h \
		../qt5pi/include/QtCore/qdatetime.h \
		../qt5pi/include/QtCore/qdeadlinetimer.h \
		../qt5pi/include/QtCore/qelapsedtimer.h \
		../qt5pi/include/QtCore/qdir.h \
		../qt5pi/include/QtCore/qfileinfo.h \
		../qt5pi/include/QtCore/qdiriterator.h \
		../qt5pi/include/QtCore/qeasingcurve.h \
		../qt5pi/include/QtCore/qendian.h \
		../qt5pi/include/QtCore/qeventtransition.h \
		../qt5pi/include/QtCore/qexception.h \
		../qt5pi/include/QtCore/qfactoryinterface.h \
		../qt5pi/include/QtCore/qfileselector.h \
		../qt5pi/include/QtCore/QObject \
		../qt5pi/include/QtCore/QStringList \
		../qt5pi/include/QtCore/qfilesystemwatcher.h \
		../qt5pi/include/QtCore/qfinalstate.h \
		../qt5pi/include/QtCore/qfuture.h \
		../qt5pi/include/QtCore/qfutureinterface.h \
		../qt5pi/include/QtCore/qrunnable.h \
		../qt5pi/include/QtCore/qresultstore.h \
		../qt5pi/include/QtCore/qfuturesynchronizer.h \
		../qt5pi/include/QtCore/qfuturewatcher.h \
		../qt5pi/include/QtCore/qhistorystate.h \
		../qt5pi/include/QtCore/qidentityproxymodel.h \
		../qt5pi/include/QtCore/qisenum.h \
		../qt5pi/include/QtCore/qitemselectionmodel.h \
		../qt5pi/include/QtCore/qjsonarray.h \
		../qt5pi/include/QtCore/qjsonvalue.h \
		../qt5pi/include/QtCore/qjsondocument.h \
		../qt5pi/include/QtCore/qjsonobject.h \
		../qt5pi/include/QtCore/qlibrary.h \
		../qt5pi/include/QtCore/qlibraryinfo.h \
		../qt5pi/include/QtCore/qversionnumber.h \
		../qt5pi/include/QtCore/qlinkedlist.h \
		../qt5pi/include/QtCore/qlockfile.h \
		../qt5pi/include/QtCore/qloggingcategory.h \
		../qt5pi/include/QtCore/qmath.h \
		../qt5pi/include/QtCore/qmessageauthenticationcode.h \
		../qt5pi/include/QtCore/qmetaobject.h \
		../qt5pi/include/QtCore/qmimedata.h \
		../qt5pi/include/QtCore/qmimedatabase.h \
		../qt5pi/include/QtCore/qmimetype.h \
		../qt5pi/include/QtCore/qobjectcleanuphandler.h \
		../qt5pi/include/QtCore/qoperatingsystemversion.h \
		../qt5pi/include/QtCore/qparallelanimationgroup.h \
		../qt5pi/include/QtCore/qpauseanimation.h \
		../qt5pi/include/QtCore/qplugin.h \
		../qt5pi/include/QtCore/qpointer.h \
		../qt5pi/include/QtCore/qpluginloader.h \
		../qt5pi/include/QtCore/qprocess.h \
		../qt5pi/include/QtCore/qpropertyanimation.h \
		../qt5pi/include/QtCore/qvariantanimation.h \
		../qt5pi/include/QtCore/qqueue.h \
		../qt5pi/include/QtCore/qrandom.h \
		../qt5pi/include/QtCore/qreadwritelock.h \
		../qt5pi/include/QtCore/qregularexpression.h \
		../qt5pi/include/QtCore/qresource.h \
		../qt5pi/include/QtCore/qsavefile.h \
		../qt5pi/include/QtCore/qscopedvaluerollback.h \
		../qt5pi/include/QtCore/qsemaphore.h \
		../qt5pi/include/QtCore/qsequentialanimationgroup.h \
		../qt5pi/include/QtCore/qsettings.h \
		../qt5pi/include/QtCore/qsharedmemory.h \
		../qt5pi/include/QtCore/qsignalmapper.h \
		../qt5pi/include/QtCore/qsignaltransition.h \
		../qt5pi/include/QtCore/qsocketnotifier.h \
		../qt5pi/include/QtCore/qsortfilterproxymodel.h \
		../qt5pi/include/QtCore/qstack.h \
		../qt5pi/include/QtCore/qstandardpaths.h \
		../qt5pi/include/QtCore/qstate.h \
		../qt5pi/include/QtCore/qstatemachine.h \
		../qt5pi/include/QtCore/qstorageinfo.h \
		../qt5pi/include/QtCore/qstringlistmodel.h \
		../qt5pi/include/QtCore/qsystemsemaphore.h \
		../qt5pi/include/QtCore/qtemporarydir.h \
		../qt5pi/include/QtCore/QScopedPointer \
		../qt5pi/include/QtCore/qtemporaryfile.h \
		../qt5pi/include/QtCore/qtextboundaryfinder.h \
		../qt5pi/include/QtCore/qtextcodec.h \
		../qt5pi/include/QtCore/qthread.h \
		../qt5pi/include/QtCore/qthreadpool.h \
		../qt5pi/include/QtCore/qthreadstorage.h \
		../qt5pi/include/QtCore/qtimeline.h \
		../qt5pi/include/QtCore/qtimer.h \
		../qt5pi/include/QtCore/qtimezone.h \
		../qt5pi/include/QtCore/qtranslator.h \
		../qt5pi/include/QtCore/qtypetraits.h \
		../qt5pi/include/QtCore/quuid.h \
		../qt5pi/include/QtCore/qwaitcondition.h \
		../qt5pi/include/QtCore/qwineventnotifier.h \
		../qt5pi/include/QtCore/qxmlstream.h \
		../qt5pi/include/QtCore/qtcoreversion.h \
		i2c_comm.h \
		EM7180_Master.h \
		EM7180.h \
		mainwidget.h \
		moc_predefs.h \
		../qt5/bin/moc
	/home/julien/raspi/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/julien/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/home/julien/raspi/JulsEfis -I/home/julien/raspi/qt5pi/include -I/home/julien/raspi/qt5pi/include/QtWidgets -I/home/julien/raspi/qt5pi/include/QtGui -I/home/julien/raspi/qt5pi/include/QtCore -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include -I/home/julien/raspi/sysroot/usr/include -I/home/julien/raspi/sysroot/usr/include/arm-linux-gnueabihf mainwidget.h -o moc_mainwidget.cpp

moc_gui.cpp: ../qt5pi/include/QtCore/QObject \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		../qt5pi/include/QtWidgets/QWidget \
		../qt5pi/include/QtWidgets/qwidget.h \
		../qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../qt5pi/include/QtGui/qtguiglobal.h \
		../qt5pi/include/QtGui/qtgui-config.h \
		../qt5pi/include/QtWidgets/qtwidgets-config.h \
		../qt5pi/include/QtGui/qwindowdefs.h \
		../qt5pi/include/QtGui/qwindowdefs_win.h \
		../qt5pi/include/QtCore/qmargins.h \
		../qt5pi/include/QtGui/qpaintdevice.h \
		../qt5pi/include/QtCore/qrect.h \
		../qt5pi/include/QtCore/qsize.h \
		../qt5pi/include/QtCore/qpoint.h \
		../qt5pi/include/QtGui/qpalette.h \
		../qt5pi/include/QtGui/qcolor.h \
		../qt5pi/include/QtGui/qrgb.h \
		../qt5pi/include/QtGui/qrgba64.h \
		../qt5pi/include/QtGui/qbrush.h \
		../qt5pi/include/QtCore/qvector.h \
		../qt5pi/include/QtGui/qmatrix.h \
		../qt5pi/include/QtGui/qpolygon.h \
		../qt5pi/include/QtGui/qregion.h \
		../qt5pi/include/QtCore/qdatastream.h \
		../qt5pi/include/QtCore/qiodevice.h \
		../qt5pi/include/QtCore/qline.h \
		../qt5pi/include/QtGui/qtransform.h \
		../qt5pi/include/QtGui/qpainterpath.h \
		../qt5pi/include/QtGui/qimage.h \
		../qt5pi/include/QtGui/qpixelformat.h \
		../qt5pi/include/QtGui/qpixmap.h \
		../qt5pi/include/QtCore/qsharedpointer.h \
		../qt5pi/include/QtCore/qshareddata.h \
		../qt5pi/include/QtCore/qhash.h \
		../qt5pi/include/QtCore/qsharedpointer_impl.h \
		../qt5pi/include/QtGui/qfont.h \
		../qt5pi/include/QtGui/qfontmetrics.h \
		../qt5pi/include/QtGui/qfontinfo.h \
		../qt5pi/include/QtWidgets/qsizepolicy.h \
		../qt5pi/include/QtGui/qcursor.h \
		../qt5pi/include/QtGui/qkeysequence.h \
		../qt5pi/include/QtGui/qevent.h \
		../qt5pi/include/QtCore/qvariant.h \
		../qt5pi/include/QtCore/qmap.h \
		../qt5pi/include/QtCore/qdebug.h \
		../qt5pi/include/QtCore/qtextstream.h \
		../qt5pi/include/QtCore/qlocale.h \
		../qt5pi/include/QtCore/qset.h \
		../qt5pi/include/QtCore/qcontiguouscache.h \
		../qt5pi/include/QtCore/qurl.h \
		../qt5pi/include/QtCore/qurlquery.h \
		../qt5pi/include/QtCore/qfile.h \
		../qt5pi/include/QtCore/qfiledevice.h \
		../qt5pi/include/QtGui/qvector2d.h \
		../qt5pi/include/QtGui/qtouchdevice.h \
		../qt5pi/include/QtGui/QColor \
		gui.h \
		moc_predefs.h \
		../qt5/bin/moc
	/home/julien/raspi/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/julien/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/home/julien/raspi/JulsEfis -I/home/julien/raspi/qt5pi/include -I/home/julien/raspi/qt5pi/include/QtWidgets -I/home/julien/raspi/qt5pi/include/QtGui -I/home/julien/raspi/qt5pi/include/QtCore -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include -I/home/julien/raspi/sysroot/usr/include -I/home/julien/raspi/sysroot/usr/include/arm-linux-gnueabihf gui.h -o moc_gui.cpp

moc_i2c_comm.cpp: ../qt5pi/include/QtCore/QObject \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		../qt5pi/include/QtCore/QtCore \
		../qt5pi/include/QtCore/QtCoreDepends \
		../qt5pi/include/QtCore/qabstractanimation.h \
		../qt5pi/include/QtCore/qabstracteventdispatcher.h \
		../qt5pi/include/QtCore/qeventloop.h \
		../qt5pi/include/QtCore/qabstractitemmodel.h \
		../qt5pi/include/QtCore/qvariant.h \
		../qt5pi/include/QtCore/qmap.h \
		../qt5pi/include/QtCore/qdebug.h \
		../qt5pi/include/QtCore/qhash.h \
		../qt5pi/include/QtCore/qtextstream.h \
		../qt5pi/include/QtCore/qiodevice.h \
		../qt5pi/include/QtCore/qlocale.h \
		../qt5pi/include/QtCore/qshareddata.h \
		../qt5pi/include/QtCore/qvector.h \
		../qt5pi/include/QtCore/qpoint.h \
		../qt5pi/include/QtCore/qset.h \
		../qt5pi/include/QtCore/qcontiguouscache.h \
		../qt5pi/include/QtCore/qsharedpointer.h \
		../qt5pi/include/QtCore/qsharedpointer_impl.h \
		../qt5pi/include/QtCore/qabstractnativeeventfilter.h \
		../qt5pi/include/QtCore/qabstractproxymodel.h \
		../qt5pi/include/QtCore/qabstractstate.h \
		../qt5pi/include/QtCore/qabstracttransition.h \
		../qt5pi/include/QtCore/qanimationgroup.h \
		../qt5pi/include/QtCore/qarraydataops.h \
		../qt5pi/include/QtCore/qarraydatapointer.h \
		../qt5pi/include/QtCore/qbasictimer.h \
		../qt5pi/include/QtCore/qbitarray.h \
		../qt5pi/include/QtCore/qbuffer.h \
		../qt5pi/include/QtCore/qbytearraymatcher.h \
		../qt5pi/include/QtCore/qcache.h \
		../qt5pi/include/QtCore/qcollator.h \
		../qt5pi/include/QtCore/qcommandlineoption.h \
		../qt5pi/include/QtCore/qcommandlineparser.h \
		../qt5pi/include/QtCore/qcoreapplication.h \
		../qt5pi/include/QtCore/qcryptographichash.h \
		../qt5pi/include/QtCore/qdatastream.h \
		../qt5pi/include/QtCore/qdatetime.h \
		../qt5pi/include/QtCore/qdeadlinetimer.h \
		../qt5pi/include/QtCore/qelapsedtimer.h \
		../qt5pi/include/QtCore/qdir.h \
		../qt5pi/include/QtCore/qfileinfo.h \
		../qt5pi/include/QtCore/qfile.h \
		../qt5pi/include/QtCore/qfiledevice.h \
		../qt5pi/include/QtCore/qdiriterator.h \
		../qt5pi/include/QtCore/qeasingcurve.h \
		../qt5pi/include/QtCore/qendian.h \
		../qt5pi/include/QtCore/qeventtransition.h \
		../qt5pi/include/QtCore/qexception.h \
		../qt5pi/include/QtCore/qfactoryinterface.h \
		../qt5pi/include/QtCore/qfileselector.h \
		../qt5pi/include/QtCore/QStringList \
		../qt5pi/include/QtCore/qfilesystemwatcher.h \
		../qt5pi/include/QtCore/qfinalstate.h \
		../qt5pi/include/QtCore/qfuture.h \
		../qt5pi/include/QtCore/qfutureinterface.h \
		../qt5pi/include/QtCore/qrunnable.h \
		../qt5pi/include/QtCore/qresultstore.h \
		../qt5pi/include/QtCore/qfuturesynchronizer.h \
		../qt5pi/include/QtCore/qfuturewatcher.h \
		../qt5pi/include/QtCore/qhistorystate.h \
		../qt5pi/include/QtCore/qidentityproxymodel.h \
		../qt5pi/include/QtCore/qisenum.h \
		../qt5pi/include/QtCore/qitemselectionmodel.h \
		../qt5pi/include/QtCore/qjsonarray.h \
		../qt5pi/include/QtCore/qjsonvalue.h \
		../qt5pi/include/QtCore/qjsondocument.h \
		../qt5pi/include/QtCore/qjsonobject.h \
		../qt5pi/include/QtCore/qlibrary.h \
		../qt5pi/include/QtCore/qlibraryinfo.h \
		../qt5pi/include/QtCore/qversionnumber.h \
		../qt5pi/include/QtCore/qline.h \
		../qt5pi/include/QtCore/qlinkedlist.h \
		../qt5pi/include/QtCore/qlockfile.h \
		../qt5pi/include/QtCore/qloggingcategory.h \
		../qt5pi/include/QtCore/qmargins.h \
		../qt5pi/include/QtCore/qmath.h \
		../qt5pi/include/QtCore/qmessageauthenticationcode.h \
		../qt5pi/include/QtCore/qmetaobject.h \
		../qt5pi/include/QtCore/qmimedata.h \
		../qt5pi/include/QtCore/qmimedatabase.h \
		../qt5pi/include/QtCore/qmimetype.h \
		../qt5pi/include/QtCore/qobjectcleanuphandler.h \
		../qt5pi/include/QtCore/qoperatingsystemversion.h \
		../qt5pi/include/QtCore/qparallelanimationgroup.h \
		../qt5pi/include/QtCore/qpauseanimation.h \
		../qt5pi/include/QtCore/qplugin.h \
		../qt5pi/include/QtCore/qpointer.h \
		../qt5pi/include/QtCore/qpluginloader.h \
		../qt5pi/include/QtCore/qprocess.h \
		../qt5pi/include/QtCore/qpropertyanimation.h \
		../qt5pi/include/QtCore/qvariantanimation.h \
		../qt5pi/include/QtCore/qqueue.h \
		../qt5pi/include/QtCore/qrandom.h \
		../qt5pi/include/QtCore/qreadwritelock.h \
		../qt5pi/include/QtCore/qrect.h \
		../qt5pi/include/QtCore/qsize.h \
		../qt5pi/include/QtCore/qregularexpression.h \
		../qt5pi/include/QtCore/qresource.h \
		../qt5pi/include/QtCore/qsavefile.h \
		../qt5pi/include/QtCore/qscopedvaluerollback.h \
		../qt5pi/include/QtCore/qsemaphore.h \
		../qt5pi/include/QtCore/qsequentialanimationgroup.h \
		../qt5pi/include/QtCore/qsettings.h \
		../qt5pi/include/QtCore/qsharedmemory.h \
		../qt5pi/include/QtCore/qsignalmapper.h \
		../qt5pi/include/QtCore/qsignaltransition.h \
		../qt5pi/include/QtCore/qsocketnotifier.h \
		../qt5pi/include/QtCore/qsortfilterproxymodel.h \
		../qt5pi/include/QtCore/qstack.h \
		../qt5pi/include/QtCore/qstandardpaths.h \
		../qt5pi/include/QtCore/qstate.h \
		../qt5pi/include/QtCore/qstatemachine.h \
		../qt5pi/include/QtCore/qstorageinfo.h \
		../qt5pi/include/QtCore/qstringlistmodel.h \
		../qt5pi/include/QtCore/qsystemsemaphore.h \
		../qt5pi/include/QtCore/qtemporarydir.h \
		../qt5pi/include/QtCore/QScopedPointer \
		../qt5pi/include/QtCore/qtemporaryfile.h \
		../qt5pi/include/QtCore/qtextboundaryfinder.h \
		../qt5pi/include/QtCore/qtextcodec.h \
		../qt5pi/include/QtCore/qthread.h \
		../qt5pi/include/QtCore/qthreadpool.h \
		../qt5pi/include/QtCore/qthreadstorage.h \
		../qt5pi/include/QtCore/qtimeline.h \
		../qt5pi/include/QtCore/qtimer.h \
		../qt5pi/include/QtCore/qtimezone.h \
		../qt5pi/include/QtCore/qtranslator.h \
		../qt5pi/include/QtCore/qtypetraits.h \
		../qt5pi/include/QtCore/qurl.h \
		../qt5pi/include/QtCore/qurlquery.h \
		../qt5pi/include/QtCore/quuid.h \
		../qt5pi/include/QtCore/qwaitcondition.h \
		../qt5pi/include/QtCore/qwineventnotifier.h \
		../qt5pi/include/QtCore/qxmlstream.h \
		../qt5pi/include/QtCore/qtcoreversion.h \
		EM7180_Master.h \
		EM7180.h \
		i2c_comm.h \
		moc_predefs.h \
		../qt5/bin/moc
	/home/julien/raspi/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/julien/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/home/julien/raspi/JulsEfis -I/home/julien/raspi/qt5pi/include -I/home/julien/raspi/qt5pi/include/QtWidgets -I/home/julien/raspi/qt5pi/include/QtGui -I/home/julien/raspi/qt5pi/include/QtCore -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/julien/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/include -I/home/julien/raspi/sysroot/usr/include -I/home/julien/raspi/sysroot/usr/include/arm-linux-gnueabihf i2c_comm.h -o moc_i2c_comm.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwidget.h
ui_mainwidget.h: mainwidget.ui \
		../qt5/bin/uic \
		gui.h \
		../qt5pi/include/QtCore/QObject \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		../qt5pi/include/QtWidgets/QWidget \
		../qt5pi/include/QtWidgets/qwidget.h \
		../qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../qt5pi/include/QtGui/qtguiglobal.h \
		../qt5pi/include/QtGui/qtgui-config.h \
		../qt5pi/include/QtWidgets/qtwidgets-config.h \
		../qt5pi/include/QtGui/qwindowdefs.h \
		../qt5pi/include/QtGui/qwindowdefs_win.h \
		../qt5pi/include/QtCore/qmargins.h \
		../qt5pi/include/QtGui/qpaintdevice.h \
		../qt5pi/include/QtCore/qrect.h \
		../qt5pi/include/QtCore/qsize.h \
		../qt5pi/include/QtCore/qpoint.h \
		../qt5pi/include/QtGui/qpalette.h \
		../qt5pi/include/QtGui/qcolor.h \
		../qt5pi/include/QtGui/qrgb.h \
		../qt5pi/include/QtGui/qrgba64.h \
		../qt5pi/include/QtGui/qbrush.h \
		../qt5pi/include/QtCore/qvector.h \
		../qt5pi/include/QtGui/qmatrix.h \
		../qt5pi/include/QtGui/qpolygon.h \
		../qt5pi/include/QtGui/qregion.h \
		../qt5pi/include/QtCore/qdatastream.h \
		../qt5pi/include/QtCore/qiodevice.h \
		../qt5pi/include/QtCore/qline.h \
		../qt5pi/include/QtGui/qtransform.h \
		../qt5pi/include/QtGui/qpainterpath.h \
		../qt5pi/include/QtGui/qimage.h \
		../qt5pi/include/QtGui/qpixelformat.h \
		../qt5pi/include/QtGui/qpixmap.h \
		../qt5pi/include/QtCore/qsharedpointer.h \
		../qt5pi/include/QtCore/qshareddata.h \
		../qt5pi/include/QtCore/qhash.h \
		../qt5pi/include/QtCore/qsharedpointer_impl.h \
		../qt5pi/include/QtGui/qfont.h \
		../qt5pi/include/QtGui/qfontmetrics.h \
		../qt5pi/include/QtGui/qfontinfo.h \
		../qt5pi/include/QtWidgets/qsizepolicy.h \
		../qt5pi/include/QtGui/qcursor.h \
		../qt5pi/include/QtGui/qkeysequence.h \
		../qt5pi/include/QtGui/qevent.h \
		../qt5pi/include/QtCore/qvariant.h \
		../qt5pi/include/QtCore/qmap.h \
		../qt5pi/include/QtCore/qdebug.h \
		../qt5pi/include/QtCore/qtextstream.h \
		../qt5pi/include/QtCore/qlocale.h \
		../qt5pi/include/QtCore/qset.h \
		../qt5pi/include/QtCore/qcontiguouscache.h \
		../qt5pi/include/QtCore/qurl.h \
		../qt5pi/include/QtCore/qurlquery.h \
		../qt5pi/include/QtCore/qfile.h \
		../qt5pi/include/QtCore/qfiledevice.h \
		../qt5pi/include/QtGui/qvector2d.h \
		../qt5pi/include/QtGui/qtouchdevice.h \
		../qt5pi/include/QtGui/QColor
	/home/julien/raspi/qt5/bin/uic mainwidget.ui -o ui_mainwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../qt5pi/include/QtWidgets/QApplication \
		../qt5pi/include/QtWidgets/qapplication.h \
		../qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../qt5pi/include/QtGui/qtguiglobal.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtGui/qtgui-config.h \
		../qt5pi/include/QtWidgets/qtwidgets-config.h \
		../qt5pi/include/QtCore/qcoreapplication.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		../qt5pi/include/QtCore/qeventloop.h \
		../qt5pi/include/QtGui/qwindowdefs.h \
		../qt5pi/include/QtGui/qwindowdefs_win.h \
		../qt5pi/include/QtCore/qpoint.h \
		../qt5pi/include/QtCore/qsize.h \
		../qt5pi/include/QtGui/qcursor.h \
		../qt5pi/include/QtWidgets/qdesktopwidget.h \
		../qt5pi/include/QtWidgets/qwidget.h \
		../qt5pi/include/QtCore/qmargins.h \
		../qt5pi/include/QtGui/qpaintdevice.h \
		../qt5pi/include/QtCore/qrect.h \
		../qt5pi/include/QtGui/qpalette.h \
		../qt5pi/include/QtGui/qcolor.h \
		../qt5pi/include/QtGui/qrgb.h \
		../qt5pi/include/QtGui/qrgba64.h \
		../qt5pi/include/QtGui/qbrush.h \
		../qt5pi/include/QtCore/qvector.h \
		../qt5pi/include/QtGui/qmatrix.h \
		../qt5pi/include/QtGui/qpolygon.h \
		../qt5pi/include/QtGui/qregion.h \
		../qt5pi/include/QtCore/qdatastream.h \
		../qt5pi/include/QtCore/qiodevice.h \
		../qt5pi/include/QtCore/qline.h \
		../qt5pi/include/QtGui/qtransform.h \
		../qt5pi/include/QtGui/qpainterpath.h \
		../qt5pi/include/QtGui/qimage.h \
		../qt5pi/include/QtGui/qpixelformat.h \
		../qt5pi/include/QtGui/qpixmap.h \
		../qt5pi/include/QtCore/qsharedpointer.h \
		../qt5pi/include/QtCore/qshareddata.h \
		../qt5pi/include/QtCore/qhash.h \
		../qt5pi/include/QtCore/qsharedpointer_impl.h \
		../qt5pi/include/QtGui/qfont.h \
		../qt5pi/include/QtGui/qfontmetrics.h \
		../qt5pi/include/QtGui/qfontinfo.h \
		../qt5pi/include/QtWidgets/qsizepolicy.h \
		../qt5pi/include/QtGui/qkeysequence.h \
		../qt5pi/include/QtGui/qevent.h \
		../qt5pi/include/QtCore/qvariant.h \
		../qt5pi/include/QtCore/qmap.h \
		../qt5pi/include/QtCore/qdebug.h \
		../qt5pi/include/QtCore/qtextstream.h \
		../qt5pi/include/QtCore/qlocale.h \
		../qt5pi/include/QtCore/qset.h \
		../qt5pi/include/QtCore/qcontiguouscache.h \
		../qt5pi/include/QtCore/qurl.h \
		../qt5pi/include/QtCore/qurlquery.h \
		../qt5pi/include/QtCore/qfile.h \
		../qt5pi/include/QtCore/qfiledevice.h \
		../qt5pi/include/QtGui/qvector2d.h \
		../qt5pi/include/QtGui/qtouchdevice.h \
		../qt5pi/include/QtGui/qguiapplication.h \
		../qt5pi/include/QtGui/qinputmethod.h \
		../qt5pi/include/QtWidgets/QMainWindow \
		../qt5pi/include/QtWidgets/qmainwindow.h \
		../qt5pi/include/QtWidgets/qtabwidget.h \
		../qt5pi/include/QtGui/qicon.h \
		../qt5pi/include/QtGui/QSurfaceFormat \
		../qt5pi/include/QtGui/qsurfaceformat.h \
		../qt5pi/include/QtCore/QCommandLineParser \
		../qt5pi/include/QtCore/qcommandlineparser.h \
		../qt5pi/include/QtCore/qcommandlineoption.h \
		../qt5pi/include/QtCore/QCommandLineOption \
		mainwidget.h \
		../qt5pi/include/QtWidgets/QWidget \
		../qt5pi/include/QtCore/QtCore \
		../qt5pi/include/QtCore/QtCoreDepends \
		../qt5pi/include/QtCore/qabstractanimation.h \
		../qt5pi/include/QtCore/qabstracteventdispatcher.h \
		../qt5pi/include/QtCore/qabstractitemmodel.h \
		../qt5pi/include/QtCore/qabstractnativeeventfilter.h \
		../qt5pi/include/QtCore/qabstractproxymodel.h \
		../qt5pi/include/QtCore/qabstractstate.h \
		../qt5pi/include/QtCore/qabstracttransition.h \
		../qt5pi/include/QtCore/qanimationgroup.h \
		../qt5pi/include/QtCore/qarraydataops.h \
		../qt5pi/include/QtCore/qarraydatapointer.h \
		../qt5pi/include/QtCore/qbasictimer.h \
		../qt5pi/include/QtCore/qbitarray.h \
		../qt5pi/include/QtCore/qbuffer.h \
		../qt5pi/include/QtCore/qbytearraymatcher.h \
		../qt5pi/include/QtCore/qcache.h \
		../qt5pi/include/QtCore/qcollator.h \
		../qt5pi/include/QtCore/qcryptographichash.h \
		../qt5pi/include/QtCore/qdatetime.h \
		../qt5pi/include/QtCore/qdeadlinetimer.h \
		../qt5pi/include/QtCore/qelapsedtimer.h \
		../qt5pi/include/QtCore/qdir.h \
		../qt5pi/include/QtCore/qfileinfo.h \
		../qt5pi/include/QtCore/qdiriterator.h \
		../qt5pi/include/QtCore/qeasingcurve.h \
		../qt5pi/include/QtCore/qendian.h \
		../qt5pi/include/QtCore/qeventtransition.h \
		../qt5pi/include/QtCore/qexception.h \
		../qt5pi/include/QtCore/qfactoryinterface.h \
		../qt5pi/include/QtCore/qfileselector.h \
		../qt5pi/include/QtCore/QObject \
		../qt5pi/include/QtCore/QStringList \
		../qt5pi/include/QtCore/qfilesystemwatcher.h \
		../qt5pi/include/QtCore/qfinalstate.h \
		../qt5pi/include/QtCore/qfuture.h \
		../qt5pi/include/QtCore/qfutureinterface.h \
		../qt5pi/include/QtCore/qrunnable.h \
		../qt5pi/include/QtCore/qresultstore.h \
		../qt5pi/include/QtCore/qfuturesynchronizer.h \
		../qt5pi/include/QtCore/qfuturewatcher.h \
		../qt5pi/include/QtCore/qhistorystate.h \
		../qt5pi/include/QtCore/qidentityproxymodel.h \
		../qt5pi/include/QtCore/qisenum.h \
		../qt5pi/include/QtCore/qitemselectionmodel.h \
		../qt5pi/include/QtCore/qjsonarray.h \
		../qt5pi/include/QtCore/qjsonvalue.h \
		../qt5pi/include/QtCore/qjsondocument.h \
		../qt5pi/include/QtCore/qjsonobject.h \
		../qt5pi/include/QtCore/qlibrary.h \
		../qt5pi/include/QtCore/qlibraryinfo.h \
		../qt5pi/include/QtCore/qversionnumber.h \
		../qt5pi/include/QtCore/qlinkedlist.h \
		../qt5pi/include/QtCore/qlockfile.h \
		../qt5pi/include/QtCore/qloggingcategory.h \
		../qt5pi/include/QtCore/qmath.h \
		../qt5pi/include/QtCore/qmessageauthenticationcode.h \
		../qt5pi/include/QtCore/qmetaobject.h \
		../qt5pi/include/QtCore/qmimedata.h \
		../qt5pi/include/QtCore/qmimedatabase.h \
		../qt5pi/include/QtCore/qmimetype.h \
		../qt5pi/include/QtCore/qobjectcleanuphandler.h \
		../qt5pi/include/QtCore/qoperatingsystemversion.h \
		../qt5pi/include/QtCore/qparallelanimationgroup.h \
		../qt5pi/include/QtCore/qpauseanimation.h \
		../qt5pi/include/QtCore/qplugin.h \
		../qt5pi/include/QtCore/qpointer.h \
		../qt5pi/include/QtCore/qpluginloader.h \
		../qt5pi/include/QtCore/qprocess.h \
		../qt5pi/include/QtCore/qpropertyanimation.h \
		../qt5pi/include/QtCore/qvariantanimation.h \
		../qt5pi/include/QtCore/qqueue.h \
		../qt5pi/include/QtCore/qrandom.h \
		../qt5pi/include/QtCore/qreadwritelock.h \
		../qt5pi/include/QtCore/qregularexpression.h \
		../qt5pi/include/QtCore/qresource.h \
		../qt5pi/include/QtCore/qsavefile.h \
		../qt5pi/include/QtCore/qscopedvaluerollback.h \
		../qt5pi/include/QtCore/qsemaphore.h \
		../qt5pi/include/QtCore/qsequentialanimationgroup.h \
		../qt5pi/include/QtCore/qsettings.h \
		../qt5pi/include/QtCore/qsharedmemory.h \
		../qt5pi/include/QtCore/qsignalmapper.h \
		../qt5pi/include/QtCore/qsignaltransition.h \
		../qt5pi/include/QtCore/qsocketnotifier.h \
		../qt5pi/include/QtCore/qsortfilterproxymodel.h \
		../qt5pi/include/QtCore/qstack.h \
		../qt5pi/include/QtCore/qstandardpaths.h \
		../qt5pi/include/QtCore/qstate.h \
		../qt5pi/include/QtCore/qstatemachine.h \
		../qt5pi/include/QtCore/qstorageinfo.h \
		../qt5pi/include/QtCore/qstringlistmodel.h \
		../qt5pi/include/QtCore/qsystemsemaphore.h \
		../qt5pi/include/QtCore/qtemporarydir.h \
		../qt5pi/include/QtCore/QScopedPointer \
		../qt5pi/include/QtCore/qtemporaryfile.h \
		../qt5pi/include/QtCore/qtextboundaryfinder.h \
		../qt5pi/include/QtCore/qtextcodec.h \
		../qt5pi/include/QtCore/qthread.h \
		../qt5pi/include/QtCore/qthreadpool.h \
		../qt5pi/include/QtCore/qthreadstorage.h \
		../qt5pi/include/QtCore/qtimeline.h \
		../qt5pi/include/QtCore/qtimer.h \
		../qt5pi/include/QtCore/qtimezone.h \
		../qt5pi/include/QtCore/qtranslator.h \
		../qt5pi/include/QtCore/qtypetraits.h \
		../qt5pi/include/QtCore/quuid.h \
		../qt5pi/include/QtCore/qwaitcondition.h \
		../qt5pi/include/QtCore/qwineventnotifier.h \
		../qt5pi/include/QtCore/qxmlstream.h \
		../qt5pi/include/QtCore/qtcoreversion.h \
		i2c_comm.h \
		EM7180_Master.h \
		EM7180.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		../qt5pi/include/QtWidgets/QWidget \
		../qt5pi/include/QtWidgets/qwidget.h \
		../qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../qt5pi/include/QtGui/qtguiglobal.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtGui/qtgui-config.h \
		../qt5pi/include/QtWidgets/qtwidgets-config.h \
		../qt5pi/include/QtGui/qwindowdefs.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtGui/qwindowdefs_win.h \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		../qt5pi/include/QtCore/qmargins.h \
		../qt5pi/include/QtGui/qpaintdevice.h \
		../qt5pi/include/QtCore/qrect.h \
		../qt5pi/include/QtCore/qsize.h \
		../qt5pi/include/QtCore/qpoint.h \
		../qt5pi/include/QtGui/qpalette.h \
		../qt5pi/include/QtGui/qcolor.h \
		../qt5pi/include/QtGui/qrgb.h \
		../qt5pi/include/QtGui/qrgba64.h \
		../qt5pi/include/QtGui/qbrush.h \
		../qt5pi/include/QtCore/qvector.h \
		../qt5pi/include/QtGui/qmatrix.h \
		../qt5pi/include/QtGui/qpolygon.h \
		../qt5pi/include/QtGui/qregion.h \
		../qt5pi/include/QtCore/qdatastream.h \
		../qt5pi/include/QtCore/qiodevice.h \
		../qt5pi/include/QtCore/qline.h \
		../qt5pi/include/QtGui/qtransform.h \
		../qt5pi/include/QtGui/qpainterpath.h \
		../qt5pi/include/QtGui/qimage.h \
		../qt5pi/include/QtGui/qpixelformat.h \
		../qt5pi/include/QtGui/qpixmap.h \
		../qt5pi/include/QtCore/qsharedpointer.h \
		../qt5pi/include/QtCore/qshareddata.h \
		../qt5pi/include/QtCore/qhash.h \
		../qt5pi/include/QtCore/qsharedpointer_impl.h \
		../qt5pi/include/QtGui/qfont.h \
		../qt5pi/include/QtGui/qfontmetrics.h \
		../qt5pi/include/QtGui/qfontinfo.h \
		../qt5pi/include/QtWidgets/qsizepolicy.h \
		../qt5pi/include/QtGui/qcursor.h \
		../qt5pi/include/QtGui/qkeysequence.h \
		../qt5pi/include/QtGui/qevent.h \
		../qt5pi/include/QtCore/qvariant.h \
		../qt5pi/include/QtCore/qmap.h \
		../qt5pi/include/QtCore/qdebug.h \
		../qt5pi/include/QtCore/qtextstream.h \
		../qt5pi/include/QtCore/qlocale.h \
		../qt5pi/include/QtCore/qset.h \
		../qt5pi/include/QtCore/qcontiguouscache.h \
		../qt5pi/include/QtCore/qurl.h \
		../qt5pi/include/QtCore/qurlquery.h \
		../qt5pi/include/QtCore/qfile.h \
		../qt5pi/include/QtCore/qfiledevice.h \
		../qt5pi/include/QtGui/qvector2d.h \
		../qt5pi/include/QtGui/qtouchdevice.h \
		../qt5pi/include/QtCore/QtCore \
		../qt5pi/include/QtCore/QtCoreDepends \
		../qt5pi/include/QtCore/qabstractanimation.h \
		../qt5pi/include/QtCore/qabstracteventdispatcher.h \
		../qt5pi/include/QtCore/qeventloop.h \
		../qt5pi/include/QtCore/qabstractitemmodel.h \
		../qt5pi/include/QtCore/qabstractnativeeventfilter.h \
		../qt5pi/include/QtCore/qabstractproxymodel.h \
		../qt5pi/include/QtCore/qabstractstate.h \
		../qt5pi/include/QtCore/qabstracttransition.h \
		../qt5pi/include/QtCore/qanimationgroup.h \
		../qt5pi/include/QtCore/qarraydataops.h \
		../qt5pi/include/QtCore/qarraydatapointer.h \
		../qt5pi/include/QtCore/qbasictimer.h \
		../qt5pi/include/QtCore/qbitarray.h \
		../qt5pi/include/QtCore/qbuffer.h \
		../qt5pi/include/QtCore/qbytearraymatcher.h \
		../qt5pi/include/QtCore/qcache.h \
		../qt5pi/include/QtCore/qcollator.h \
		../qt5pi/include/QtCore/qcommandlineoption.h \
		../qt5pi/include/QtCore/qcommandlineparser.h \
		../qt5pi/include/QtCore/qcoreapplication.h \
		../qt5pi/include/QtCore/qcryptographichash.h \
		../qt5pi/include/QtCore/qdatetime.h \
		../qt5pi/include/QtCore/qdeadlinetimer.h \
		../qt5pi/include/QtCore/qelapsedtimer.h \
		../qt5pi/include/QtCore/qdir.h \
		../qt5pi/include/QtCore/qfileinfo.h \
		../qt5pi/include/QtCore/qdiriterator.h \
		../qt5pi/include/QtCore/qeasingcurve.h \
		../qt5pi/include/QtCore/qendian.h \
		../qt5pi/include/QtCore/qeventtransition.h \
		../qt5pi/include/QtCore/qexception.h \
		../qt5pi/include/QtCore/qfactoryinterface.h \
		../qt5pi/include/QtCore/qfileselector.h \
		../qt5pi/include/QtCore/QObject \
		../qt5pi/include/QtCore/QStringList \
		../qt5pi/include/QtCore/qfilesystemwatcher.h \
		../qt5pi/include/QtCore/qfinalstate.h \
		../qt5pi/include/QtCore/qfuture.h \
		../qt5pi/include/QtCore/qfutureinterface.h \
		../qt5pi/include/QtCore/qrunnable.h \
		../qt5pi/include/QtCore/qresultstore.h \
		../qt5pi/include/QtCore/qfuturesynchronizer.h \
		../qt5pi/include/QtCore/qfuturewatcher.h \
		../qt5pi/include/QtCore/qhistorystate.h \
		../qt5pi/include/QtCore/qidentityproxymodel.h \
		../qt5pi/include/QtCore/qisenum.h \
		../qt5pi/include/QtCore/qitemselectionmodel.h \
		../qt5pi/include/QtCore/qjsonarray.h \
		../qt5pi/include/QtCore/qjsonvalue.h \
		../qt5pi/include/QtCore/qjsondocument.h \
		../qt5pi/include/QtCore/qjsonobject.h \
		../qt5pi/include/QtCore/qlibrary.h \
		../qt5pi/include/QtCore/qlibraryinfo.h \
		../qt5pi/include/QtCore/qversionnumber.h \
		../qt5pi/include/QtCore/qlinkedlist.h \
		../qt5pi/include/QtCore/qlockfile.h \
		../qt5pi/include/QtCore/qloggingcategory.h \
		../qt5pi/include/QtCore/qmath.h \
		../qt5pi/include/QtCore/qmessageauthenticationcode.h \
		../qt5pi/include/QtCore/qmetaobject.h \
		../qt5pi/include/QtCore/qmimedata.h \
		../qt5pi/include/QtCore/qmimedatabase.h \
		../qt5pi/include/QtCore/qmimetype.h \
		../qt5pi/include/QtCore/qobjectcleanuphandler.h \
		../qt5pi/include/QtCore/qoperatingsystemversion.h \
		../qt5pi/include/QtCore/qparallelanimationgroup.h \
		../qt5pi/include/QtCore/qpauseanimation.h \
		../qt5pi/include/QtCore/qplugin.h \
		../qt5pi/include/QtCore/qpointer.h \
		../qt5pi/include/QtCore/qpluginloader.h \
		../qt5pi/include/QtCore/qprocess.h \
		../qt5pi/include/QtCore/qpropertyanimation.h \
		../qt5pi/include/QtCore/qvariantanimation.h \
		../qt5pi/include/QtCore/qqueue.h \
		../qt5pi/include/QtCore/qrandom.h \
		../qt5pi/include/QtCore/qreadwritelock.h \
		../qt5pi/include/QtCore/qregularexpression.h \
		../qt5pi/include/QtCore/qresource.h \
		../qt5pi/include/QtCore/qsavefile.h \
		../qt5pi/include/QtCore/qscopedvaluerollback.h \
		../qt5pi/include/QtCore/qsemaphore.h \
		../qt5pi/include/QtCore/qsequentialanimationgroup.h \
		../qt5pi/include/QtCore/qsettings.h \
		../qt5pi/include/QtCore/qsharedmemory.h \
		../qt5pi/include/QtCore/qsignalmapper.h \
		../qt5pi/include/QtCore/qsignaltransition.h \
		../qt5pi/include/QtCore/qsocketnotifier.h \
		../qt5pi/include/QtCore/qsortfilterproxymodel.h \
		../qt5pi/include/QtCore/qstack.h \
		../qt5pi/include/QtCore/qstandardpaths.h \
		../qt5pi/include/QtCore/qstate.h \
		../qt5pi/include/QtCore/qstatemachine.h \
		../qt5pi/include/QtCore/qstorageinfo.h \
		../qt5pi/include/QtCore/qstringlistmodel.h \
		../qt5pi/include/QtCore/qsystemsemaphore.h \
		../qt5pi/include/QtCore/qtemporarydir.h \
		../qt5pi/include/QtCore/QScopedPointer \
		../qt5pi/include/QtCore/qtemporaryfile.h \
		../qt5pi/include/QtCore/qtextboundaryfinder.h \
		../qt5pi/include/QtCore/qtextcodec.h \
		../qt5pi/include/QtCore/qthread.h \
		../qt5pi/include/QtCore/qthreadpool.h \
		../qt5pi/include/QtCore/qthreadstorage.h \
		../qt5pi/include/QtCore/qtimeline.h \
		../qt5pi/include/QtCore/qtimer.h \
		../qt5pi/include/QtCore/qtimezone.h \
		../qt5pi/include/QtCore/qtranslator.h \
		../qt5pi/include/QtCore/qtypetraits.h \
		../qt5pi/include/QtCore/quuid.h \
		../qt5pi/include/QtCore/qwaitcondition.h \
		../qt5pi/include/QtCore/qwineventnotifier.h \
		../qt5pi/include/QtCore/qxmlstream.h \
		../qt5pi/include/QtCore/qtcoreversion.h \
		i2c_comm.h \
		EM7180_Master.h \
		EM7180.h \
		ui_mainwidget.h \
		../qt5pi/include/QtCore/QVariant \
		../qt5pi/include/QtWidgets/QAction \
		../qt5pi/include/QtWidgets/qaction.h \
		../qt5pi/include/QtGui/qicon.h \
		../qt5pi/include/QtWidgets/qactiongroup.h \
		../qt5pi/include/QtWidgets/QApplication \
		../qt5pi/include/QtWidgets/qapplication.h \
		../qt5pi/include/QtWidgets/qdesktopwidget.h \
		../qt5pi/include/QtGui/qguiapplication.h \
		../qt5pi/include/QtGui/qinputmethod.h \
		../qt5pi/include/QtWidgets/QButtonGroup \
		../qt5pi/include/QtWidgets/qbuttongroup.h \
		../qt5pi/include/QtWidgets/QFrame \
		../qt5pi/include/QtWidgets/qframe.h \
		../qt5pi/include/QtWidgets/QGridLayout \
		../qt5pi/include/QtWidgets/qgridlayout.h \
		../qt5pi/include/QtWidgets/qlayout.h \
		../qt5pi/include/QtWidgets/qlayoutitem.h \
		../qt5pi/include/QtWidgets/qboxlayout.h \
		../qt5pi/include/QtWidgets/QHeaderView \
		../qt5pi/include/QtWidgets/qheaderview.h \
		../qt5pi/include/QtWidgets/qabstractitemview.h \
		../qt5pi/include/QtWidgets/qabstractscrollarea.h \
		../qt5pi/include/QtWidgets/qabstractitemdelegate.h \
		../qt5pi/include/QtWidgets/qstyleoption.h \
		../qt5pi/include/QtWidgets/qabstractspinbox.h \
		../qt5pi/include/QtGui/qvalidator.h \
		../qt5pi/include/QtWidgets/qslider.h \
		../qt5pi/include/QtWidgets/qabstractslider.h \
		../qt5pi/include/QtWidgets/qstyle.h \
		../qt5pi/include/QtWidgets/qtabbar.h \
		../qt5pi/include/QtWidgets/qtabwidget.h \
		../qt5pi/include/QtWidgets/qrubberband.h \
		../qt5pi/include/QtWidgets/QLabel \
		../qt5pi/include/QtWidgets/qlabel.h \
		../qt5pi/include/QtWidgets/QPushButton \
		../qt5pi/include/QtWidgets/qpushbutton.h \
		../qt5pi/include/QtWidgets/qabstractbutton.h \
		../qt5pi/include/QtWidgets/QSlider \
		gui.h \
		../qt5pi/include/QtGui/QColor \
		../qt5pi/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

EM7180.o: EM7180.cpp EM7180.h \
		bcm2835.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EM7180.o EM7180.cpp

EM7180_Master.o: EM7180_Master.cpp EM7180_Master.h \
		EM7180.h \
		../qt5pi/include/QtCore/QThread \
		../qt5pi/include/QtCore/qthread.h \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		CrossPlatformI2C_Core.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EM7180_Master.o EM7180_Master.cpp

gui.o: gui.cpp gui.h \
		../qt5pi/include/QtCore/QObject \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		../qt5pi/include/QtWidgets/QWidget \
		../qt5pi/include/QtWidgets/qwidget.h \
		../qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../qt5pi/include/QtGui/qtguiglobal.h \
		../qt5pi/include/QtGui/qtgui-config.h \
		../qt5pi/include/QtWidgets/qtwidgets-config.h \
		../qt5pi/include/QtGui/qwindowdefs.h \
		../qt5pi/include/QtGui/qwindowdefs_win.h \
		../qt5pi/include/QtCore/qmargins.h \
		../qt5pi/include/QtGui/qpaintdevice.h \
		../qt5pi/include/QtCore/qrect.h \
		../qt5pi/include/QtCore/qsize.h \
		../qt5pi/include/QtCore/qpoint.h \
		../qt5pi/include/QtGui/qpalette.h \
		../qt5pi/include/QtGui/qcolor.h \
		../qt5pi/include/QtGui/qrgb.h \
		../qt5pi/include/QtGui/qrgba64.h \
		../qt5pi/include/QtGui/qbrush.h \
		../qt5pi/include/QtCore/qvector.h \
		../qt5pi/include/QtGui/qmatrix.h \
		../qt5pi/include/QtGui/qpolygon.h \
		../qt5pi/include/QtGui/qregion.h \
		../qt5pi/include/QtCore/qdatastream.h \
		../qt5pi/include/QtCore/qiodevice.h \
		../qt5pi/include/QtCore/qline.h \
		../qt5pi/include/QtGui/qtransform.h \
		../qt5pi/include/QtGui/qpainterpath.h \
		../qt5pi/include/QtGui/qimage.h \
		../qt5pi/include/QtGui/qpixelformat.h \
		../qt5pi/include/QtGui/qpixmap.h \
		../qt5pi/include/QtCore/qsharedpointer.h \
		../qt5pi/include/QtCore/qshareddata.h \
		../qt5pi/include/QtCore/qhash.h \
		../qt5pi/include/QtCore/qsharedpointer_impl.h \
		../qt5pi/include/QtGui/qfont.h \
		../qt5pi/include/QtGui/qfontmetrics.h \
		../qt5pi/include/QtGui/qfontinfo.h \
		../qt5pi/include/QtWidgets/qsizepolicy.h \
		../qt5pi/include/QtGui/qcursor.h \
		../qt5pi/include/QtGui/qkeysequence.h \
		../qt5pi/include/QtGui/qevent.h \
		../qt5pi/include/QtCore/qvariant.h \
		../qt5pi/include/QtCore/qmap.h \
		../qt5pi/include/QtCore/qdebug.h \
		../qt5pi/include/QtCore/qtextstream.h \
		../qt5pi/include/QtCore/qlocale.h \
		../qt5pi/include/QtCore/qset.h \
		../qt5pi/include/QtCore/qcontiguouscache.h \
		../qt5pi/include/QtCore/qurl.h \
		../qt5pi/include/QtCore/qurlquery.h \
		../qt5pi/include/QtCore/qfile.h \
		../qt5pi/include/QtCore/qfiledevice.h \
		../qt5pi/include/QtGui/qvector2d.h \
		../qt5pi/include/QtGui/qtouchdevice.h \
		../qt5pi/include/QtGui/QColor \
		../qt5pi/include/QtGui/QPainter \
		../qt5pi/include/QtGui/qpainter.h \
		../qt5pi/include/QtGui/qtextoption.h \
		../qt5pi/include/QtGui/qpen.h \
		../qt5pi/include/QtCore/QtMath \
		../qt5pi/include/QtCore/qmath.h \
		../qt5pi/include/QtWidgets/QFrame \
		../qt5pi/include/QtWidgets/qframe.h \
		../qt5pi/include/QtWidgets/QHBoxLayout \
		../qt5pi/include/QtWidgets/qboxlayout.h \
		../qt5pi/include/QtWidgets/qlayout.h \
		../qt5pi/include/QtWidgets/qlayoutitem.h \
		../qt5pi/include/QtWidgets/qgridlayout.h \
		../qt5pi/include/QtCore/QTextStream
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gui.o gui.cpp

i2c_comm.o: i2c_comm.cpp i2c_comm.h \
		../qt5pi/include/QtCore/QObject \
		../qt5pi/include/QtCore/qobject.h \
		../qt5pi/include/QtCore/qobjectdefs.h \
		../qt5pi/include/QtCore/qnamespace.h \
		../qt5pi/include/QtCore/qglobal.h \
		../qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../qt5pi/include/QtCore/qconfig.h \
		../qt5pi/include/QtCore/qtcore-config.h \
		../qt5pi/include/QtCore/qsystemdetection.h \
		../qt5pi/include/QtCore/qprocessordetection.h \
		../qt5pi/include/QtCore/qcompilerdetection.h \
		../qt5pi/include/QtCore/qtypeinfo.h \
		../qt5pi/include/QtCore/qsysinfo.h \
		../qt5pi/include/QtCore/qlogging.h \
		../qt5pi/include/QtCore/qflags.h \
		../qt5pi/include/QtCore/qatomic.h \
		../qt5pi/include/QtCore/qbasicatomic.h \
		../qt5pi/include/QtCore/qatomic_bootstrap.h \
		../qt5pi/include/QtCore/qgenericatomic.h \
		../qt5pi/include/QtCore/qatomic_cxx11.h \
		../qt5pi/include/QtCore/qatomic_msvc.h \
		../qt5pi/include/QtCore/qglobalstatic.h \
		../qt5pi/include/QtCore/qmutex.h \
		../qt5pi/include/QtCore/qnumeric.h \
		../qt5pi/include/QtCore/qversiontagging.h \
		../qt5pi/include/QtCore/qobjectdefs_impl.h \
		../qt5pi/include/QtCore/qstring.h \
		../qt5pi/include/QtCore/qchar.h \
		../qt5pi/include/QtCore/qbytearray.h \
		../qt5pi/include/QtCore/qrefcount.h \
		../qt5pi/include/QtCore/qarraydata.h \
		../qt5pi/include/QtCore/qstringliteral.h \
		../qt5pi/include/QtCore/qstringalgorithms.h \
		../qt5pi/include/QtCore/qstringview.h \
		../qt5pi/include/QtCore/qstringbuilder.h \
		../qt5pi/include/QtCore/qlist.h \
		../qt5pi/include/QtCore/qalgorithms.h \
		../qt5pi/include/QtCore/qiterator.h \
		../qt5pi/include/QtCore/qhashfunctions.h \
		../qt5pi/include/QtCore/qpair.h \
		../qt5pi/include/QtCore/qbytearraylist.h \
		../qt5pi/include/QtCore/qstringlist.h \
		../qt5pi/include/QtCore/qregexp.h \
		../qt5pi/include/QtCore/qstringmatcher.h \
		../qt5pi/include/QtCore/qcoreevent.h \
		../qt5pi/include/QtCore/qscopedpointer.h \
		../qt5pi/include/QtCore/qmetatype.h \
		../qt5pi/include/QtCore/qvarlengtharray.h \
		../qt5pi/include/QtCore/qcontainerfwd.h \
		../qt5pi/include/QtCore/qobject_impl.h \
		../qt5pi/include/QtCore/QtCore \
		../qt5pi/include/QtCore/QtCoreDepends \
		../qt5pi/include/QtCore/qabstractanimation.h \
		../qt5pi/include/QtCore/qabstracteventdispatcher.h \
		../qt5pi/include/QtCore/qeventloop.h \
		../qt5pi/include/QtCore/qabstractitemmodel.h \
		../qt5pi/include/QtCore/qvariant.h \
		../qt5pi/include/QtCore/qmap.h \
		../qt5pi/include/QtCore/qdebug.h \
		../qt5pi/include/QtCore/qhash.h \
		../qt5pi/include/QtCore/qtextstream.h \
		../qt5pi/include/QtCore/qiodevice.h \
		../qt5pi/include/QtCore/qlocale.h \
		../qt5pi/include/QtCore/qshareddata.h \
		../qt5pi/include/QtCore/qvector.h \
		../qt5pi/include/QtCore/qpoint.h \
		../qt5pi/include/QtCore/qset.h \
		../qt5pi/include/QtCore/qcontiguouscache.h \
		../qt5pi/include/QtCore/qsharedpointer.h \
		../qt5pi/include/QtCore/qsharedpointer_impl.h \
		../qt5pi/include/QtCore/qabstractnativeeventfilter.h \
		../qt5pi/include/QtCore/qabstractproxymodel.h \
		../qt5pi/include/QtCore/qabstractstate.h \
		../qt5pi/include/QtCore/qabstracttransition.h \
		../qt5pi/include/QtCore/qanimationgroup.h \
		../qt5pi/include/QtCore/qarraydataops.h \
		../qt5pi/include/QtCore/qarraydatapointer.h \
		../qt5pi/include/QtCore/qbasictimer.h \
		../qt5pi/include/QtCore/qbitarray.h \
		../qt5pi/include/QtCore/qbuffer.h \
		../qt5pi/include/QtCore/qbytearraymatcher.h \
		../qt5pi/include/QtCore/qcache.h \
		../qt5pi/include/QtCore/qcollator.h \
		../qt5pi/include/QtCore/qcommandlineoption.h \
		../qt5pi/include/QtCore/qcommandlineparser.h \
		../qt5pi/include/QtCore/qcoreapplication.h \
		../qt5pi/include/QtCore/qcryptographichash.h \
		../qt5pi/include/QtCore/qdatastream.h \
		../qt5pi/include/QtCore/qdatetime.h \
		../qt5pi/include/QtCore/qdeadlinetimer.h \
		../qt5pi/include/QtCore/qelapsedtimer.h \
		../qt5pi/include/QtCore/qdir.h \
		../qt5pi/include/QtCore/qfileinfo.h \
		../qt5pi/include/QtCore/qfile.h \
		../qt5pi/include/QtCore/qfiledevice.h \
		../qt5pi/include/QtCore/qdiriterator.h \
		../qt5pi/include/QtCore/qeasingcurve.h \
		../qt5pi/include/QtCore/qendian.h \
		../qt5pi/include/QtCore/qeventtransition.h \
		../qt5pi/include/QtCore/qexception.h \
		../qt5pi/include/QtCore/qfactoryinterface.h \
		../qt5pi/include/QtCore/qfileselector.h \
		../qt5pi/include/QtCore/QStringList \
		../qt5pi/include/QtCore/qfilesystemwatcher.h \
		../qt5pi/include/QtCore/qfinalstate.h \
		../qt5pi/include/QtCore/qfuture.h \
		../qt5pi/include/QtCore/qfutureinterface.h \
		../qt5pi/include/QtCore/qrunnable.h \
		../qt5pi/include/QtCore/qresultstore.h \
		../qt5pi/include/QtCore/qfuturesynchronizer.h \
		../qt5pi/include/QtCore/qfuturewatcher.h \
		../qt5pi/include/QtCore/qhistorystate.h \
		../qt5pi/include/QtCore/qidentityproxymodel.h \
		../qt5pi/include/QtCore/qisenum.h \
		../qt5pi/include/QtCore/qitemselectionmodel.h \
		../qt5pi/include/QtCore/qjsonarray.h \
		../qt5pi/include/QtCore/qjsonvalue.h \
		../qt5pi/include/QtCore/qjsondocument.h \
		../qt5pi/include/QtCore/qjsonobject.h \
		../qt5pi/include/QtCore/qlibrary.h \
		../qt5pi/include/QtCore/qlibraryinfo.h \
		../qt5pi/include/QtCore/qversionnumber.h \
		../qt5pi/include/QtCore/qline.h \
		../qt5pi/include/QtCore/qlinkedlist.h \
		../qt5pi/include/QtCore/qlockfile.h \
		../qt5pi/include/QtCore/qloggingcategory.h \
		../qt5pi/include/QtCore/qmargins.h \
		../qt5pi/include/QtCore/qmath.h \
		../qt5pi/include/QtCore/qmessageauthenticationcode.h \
		../qt5pi/include/QtCore/qmetaobject.h \
		../qt5pi/include/QtCore/qmimedata.h \
		../qt5pi/include/QtCore/qmimedatabase.h \
		../qt5pi/include/QtCore/qmimetype.h \
		../qt5pi/include/QtCore/qobjectcleanuphandler.h \
		../qt5pi/include/QtCore/qoperatingsystemversion.h \
		../qt5pi/include/QtCore/qparallelanimationgroup.h \
		../qt5pi/include/QtCore/qpauseanimation.h \
		../qt5pi/include/QtCore/qplugin.h \
		../qt5pi/include/QtCore/qpointer.h \
		../qt5pi/include/QtCore/qpluginloader.h \
		../qt5pi/include/QtCore/qprocess.h \
		../qt5pi/include/QtCore/qpropertyanimation.h \
		../qt5pi/include/QtCore/qvariantanimation.h \
		../qt5pi/include/QtCore/qqueue.h \
		../qt5pi/include/QtCore/qrandom.h \
		../qt5pi/include/QtCore/qreadwritelock.h \
		../qt5pi/include/QtCore/qrect.h \
		../qt5pi/include/QtCore/qsize.h \
		../qt5pi/include/QtCore/qregularexpression.h \
		../qt5pi/include/QtCore/qresource.h \
		../qt5pi/include/QtCore/qsavefile.h \
		../qt5pi/include/QtCore/qscopedvaluerollback.h \
		../qt5pi/include/QtCore/qsemaphore.h \
		../qt5pi/include/QtCore/qsequentialanimationgroup.h \
		../qt5pi/include/QtCore/qsettings.h \
		../qt5pi/include/QtCore/qsharedmemory.h \
		../qt5pi/include/QtCore/qsignalmapper.h \
		../qt5pi/include/QtCore/qsignaltransition.h \
		../qt5pi/include/QtCore/qsocketnotifier.h \
		../qt5pi/include/QtCore/qsortfilterproxymodel.h \
		../qt5pi/include/QtCore/qstack.h \
		../qt5pi/include/QtCore/qstandardpaths.h \
		../qt5pi/include/QtCore/qstate.h \
		../qt5pi/include/QtCore/qstatemachine.h \
		../qt5pi/include/QtCore/qstorageinfo.h \
		../qt5pi/include/QtCore/qstringlistmodel.h \
		../qt5pi/include/QtCore/qsystemsemaphore.h \
		../qt5pi/include/QtCore/qtemporarydir.h \
		../qt5pi/include/QtCore/QScopedPointer \
		../qt5pi/include/QtCore/qtemporaryfile.h \
		../qt5pi/include/QtCore/qtextboundaryfinder.h \
		../qt5pi/include/QtCore/qtextcodec.h \
		../qt5pi/include/QtCore/qthread.h \
		../qt5pi/include/QtCore/qthreadpool.h \
		../qt5pi/include/QtCore/qthreadstorage.h \
		../qt5pi/include/QtCore/qtimeline.h \
		../qt5pi/include/QtCore/qtimer.h \
		../qt5pi/include/QtCore/qtimezone.h \
		../qt5pi/include/QtCore/qtranslator.h \
		../qt5pi/include/QtCore/qtypetraits.h \
		../qt5pi/include/QtCore/qurl.h \
		../qt5pi/include/QtCore/qurlquery.h \
		../qt5pi/include/QtCore/quuid.h \
		../qt5pi/include/QtCore/qwaitcondition.h \
		../qt5pi/include/QtCore/qwineventnotifier.h \
		../qt5pi/include/QtCore/qxmlstream.h \
		../qt5pi/include/QtCore/qtcoreversion.h \
		EM7180_Master.h \
		EM7180.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o i2c_comm.o i2c_comm.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_gui.o: moc_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gui.o moc_gui.cpp

moc_i2c_comm.o: moc_i2c_comm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_i2c_comm.o moc_i2c_comm.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/julien/raspi/qt5pi/examples/opengl/qopenglwidget || mkdir -p $(INSTALL_ROOT)/home/julien/raspi/qt5pi/examples/opengl/qopenglwidget
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/julien/raspi/qt5pi/examples/opengl/qopenglwidget/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/julien/raspi/qt5pi/examples/opengl/qopenglwidget/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/julien/raspi/qt5pi/examples/opengl/qopenglwidget/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

